Right now I should really just ignore this entire file, and just make a countdown system that works. That's it, that's the priority. After that I can look back here and work on implementing this stuff.


* TODO
** TODO Countdown Logic
- [ ] Handle DST
- [ ] Handle negative countdowns
** TODO Misc.
- [ ] Add config file [0/1]
  - [ ] Setting countdown pools
- [ ] Add repository of countdown pools
- [ ] Decide countdown file structure
  Should have the settings for each countdown like what to display (hours, minutes, days, etc...), a title, a date to count down to (obviously, but which format?)
- [ ] Add countdown creation menu
- [ ] Add countdown deletion
- [ ] Make countdown actually work.
* Settings
** Deletion
Countdowns could be automatically "deleted" based on per-countdown setting or global configuration. Deletion could be just normal deletion of the file or the file could be moved to a "graveyard" directory with old countdowns archived.
Deletion should probably have a grace period, meaning it'd only get deleted automatically after some time.
